import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Employees.module.css'


export async function getStaticProps() {
  const req = await fetch('https://jsonplaceholder.typicode.com/users')
  const res = await req.json()
  const data = await res.slice(0, 50)

  return {
    props: { data }
  }
}

export default function Employees({ data }) {

  return (
    <div>
      <Head>
        <title>Next Test | Employees</title>
        <meta name="description" content="Generated By Esrafil Elahi" />
      </Head>

      <h1 className={styles.home}>Hello Employees</h1><hr/>
      <div className={styles.container}></div>

      {
        data.map(item => {
          return (
            <div key={item.id} className={styles.container}>
              <h4 className={styles.name}><Link  href={`/employees/${item.id}`}>{item.name}</Link></h4>
            </div>
          )
        })
      }

    </div>
  )
}

